name: Create Release in Altinn Studio

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Mirror to Gitea"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Latest Release Info from Gitea
      id: get-release
      run: |
        RESPONSE=$(curl -s "https://altinn.studio/designer/api/digdir/nlunde-test/releases")
        echo "::set-output name=response::$RESPONSE"

    - name: Parse Response and Get Latest Release Number
      id: parse-release
      run: |
        LATEST_RELEASE=$(echo '${{ steps.get-release.outputs.response }}' | jq '[.results[] | select(.build.status == "completed")] | max_by(.tagName | tonumber)')
        TAG_NAME=$(echo $LATEST_RELEASE | jq -r '.tagName')
        COMMITISH=$(echo $LATEST_RELEASE | jq -r '.targetCommitish')
        echo "::set-output name=tag_name::$TAG_NAME"
        echo "::set-output name=commitish::$COMMITISH"

    - name: Get Latest Commit in GitHub Repo
      id: get-latest-commit
      run: |
        LATEST_COMMIT_HASH=$(git rev-parse HEAD)
        LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "::set-output name=latest_commit_hash::$LATEST_COMMIT_HASH"
        echo "::set-output name=latest_commit_message::$LATEST_COMMIT_MESSAGE"

    - name: Check if New Release is Needed
      id: check-release
      run: |
        if [ "${{ steps.parse-release.outputs.commitish }}" != "${{ steps.get-latest-commit.outputs.latest_commit_hash }}" ]; then
          NEW_TAG=$(( ${{ steps.parse-release.outputs.tag_name }} + 1 ))
          echo "::set-output name=new_tag::$NEW_TAG"
        else
          echo "No new release needed"
          echo "exit 1"

    - name: Create New Release in Gitea
      if: steps.check-release.outputs.new_tag != ''
      run: |
        NEW_TAG=${{ steps.check-release.outputs.new_tag }}
        COMMIT_MESSAGE=${{ steps.get-latest-commit.outputs.latest_commit_message }}
        COMMIT_HASH=${{ steps.get-latest-commit.outputs.latest_commit_hash }}
        BODY="{\"tagName\": \"$NEW_TAG\", \"name\": \"$NEW_TAG\", \"body\": \"$COMMIT_MESSAGE\", \"targetCommitish\": \"$COMMIT_HASH\"}"
        curl -X POST "https://altinn.studio/designer/api/digdir/nlunde-test/releases" -d "$BODY"
