name: Mirror to Gitea

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to Gitea
      run: |
        git remote add gitea https://nlunde:${{ secrets.GITEA_ACCESS_TOKEN }}@altinn.studio/repos/digdir/nlunde-test.git
        git push --force gitea HEAD:master
